FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev

# Copy Certs
WORKDIR /usr/local/share/ca-certificates
COPY ./simple-budget/certs/ca ./

#update the certificates for the container
RUN update-ca-certificates 

WORKDIR /https
COPY ./simple-budget/certs/https ./

# Copy Packages to /app/packages
WORKDIR /app/packages
COPY ./packages ./

# Add NuGet source: Local
RUN dotnet nuget add source /app/packages -n local

# Copy Main Project and dependencies
WORKDIR /app/src
COPY ./api/src/simple-budget.api ./simple-budget.api
COPY ./api/src/simple-budget.api.data ./simple-budget.api.data

# Build package
WORKDIR /app/src/simple-budget.api
RUN dotnet build ./simple-budget.api.csproj

ENTRYPOINT [ "dotnet", "watch", "run", "./simple-budget.api.csproj" ]