@api_HostAddress = https://localhost:3102/api
@accessToken=eyJhbGciOiJSUzI1NiIsImtpZCI6IkEwMEM4QzRDQUQ2RENEMjFGOTQxMzE1MUFFNEQ3NzNCIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMTAzIiwibmJmIjoxNzAyNjk0OTU0LCJpYXQiOjE3MDI2OTQ5NTQsImV4cCI6MTcwMjY5ODU1NCwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwidXNlciIsInNpbXBsZS1idWRnZXQtYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJiYWNrZW5kLWZvci1mcm9udGVuZCIsInN1YiI6IjU5ODliNzE3LWViNTUtNDdiZS1hN2U5LTAxOWIxY2FmZjAwZiIsImF1dGhfdGltZSI6MTcwMjY5NDk1NCwiaWRwIjoibG9jYWwiLCJzaWQiOiJCNUU5MzI3Q0JDNDJGMzc3MDVGNzAyMjU2RTUxMUMyQSIsImp0aSI6IkQxM0M5ODU4OEJCREY3OUYyNTE0QzYwMEY4NDQ2NEZFIn0.oYLiBEF1XmUCmFUdgcnyAdEcD18be9BmpQhkKYtb2hPXAa0JZPAnjirxJ16FYOX6AOItx1dSWJwUxHKYiihsSue2aV6gdMLl3HnIRYU3LlHIX1kVAxCMdhudtFrv6IqMY58mQ3kHyr-rF8FxNWOlc1E6haZOMHjDnPjr29vWtBJWmzPWrD2adYm2fngjavd-sy1PtWTEYOCDANZacTejiKH8PfONxEwdM0nKMYoOr-lyPk1onvA__r4vt4xZm1-t975gd8Ol28KLShpHNs03wkvw5dVbR75n1G14lxFVhW33bdgGs-gSp-T2_bQlXlonPy3Z4-APsB7QVho02UarWg

GET {{api_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{accessToken}}

###
